name: efood_kitchen
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  shared_preferences: ^2.0.15
  connectivity_plus: ^5.0.2
  firebase_core: ^2.2.0
  firebase_messaging: ^14.1.0
  flutter_local_notifications: ^16.3.3
  path_provider: ^2.0.11
  url_strategy: ^0.2.0
  image_picker: ^1.0.7
  cached_network_image: ^3.2.2
  country_code_picker: ^3.0.0
  vibration: ^1.7.4-nullsafety.0
  shimmer: ^3.0.0
  flutter_custom_clippers: ^2.0.0
  flutter_spinkit: ^5.1.0
  audioplayers: ^5.2.1
  http: ^1.2.1
  permission_handler: ^11.3.0
  intl: ^0.19.0
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900



