// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN0JnCA62GjLv-1Fq7-yzu04LiBA1Pflg',
    appId: '1:422386866717:web:1d2e882f14a6ffae0304f4',
    messagingSenderId: '422386866717',
    projectId: 'cit-efood',
    authDomain: 'cit-efood.firebaseapp.com',
    storageBucket: 'cit-efood.appspot.com',
    measurementId: 'G-ZERB2HCK04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxgc7U3TfV_JHzOMCpOL72ykGWkOr8FJY',
    appId: '1:422386866717:android:ed295337addd2ade0304f4',
    messagingSenderId: '422386866717',
    projectId: 'cit-efood',
    storageBucket: 'cit-efood.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXT8N2IehCzBrtgC1h25tMhr-HW1XukAg',
    appId: '1:422386866717:ios:aadd5c5399c5f61e0304f4',
    messagingSenderId: '422386866717',
    projectId: 'cit-efood',
    storageBucket: 'cit-efood.appspot.com',
    iosBundleId: 'com.u6amtech.flutterRestaurant',
  );
}
