name: citgroupvn_eshop_seller
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  provider: ^6.0.2
  connectivity: ^3.0.6
  dio: ^4.0.0-prev2
  intl: ^0.18.0
  shared_preferences: ^2.0.5
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  flutter_switch: ^0.3.0
  fl_chart: ^0.55.1
  # cached_network_image: ^3.1.0
  cached_network_image: ^3.3.0
  flutter_typeahead: ^4.0.0 
  autocomplete_textfield: ^2.0.1
  dotted_border: ^2.0.0+1
  flutter_html: ^3.0.0-alpha.2
  firebase_core: ^2.10.0
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^9.0.0
  path_provider: ^2.0.1
  country_code_picker: ^3.0.0
  pin_code_fields: ^8.0.1
  fluttertoast: ^8.0.9
  permission_handler: ^11.3.0
  barcode_widget: ^2.0.2
  file_picker: ^6.2.0
  url_launcher: ^6.1.5
  flutter_spinkit: ^5.1.0
  percent_indicator: ^4.2.2
  flutter_speed_dial: ^7.0.0
  flutter_barcode_scanner: ^2.0.0
  flutter_pos_printer_platform: ^1.0.9
  esc_pos_utils: ^1.1.0
  flutter_slidable: ^3.0.1
  readmore: ^2.2.0
  flutter_html_table: ^3.0.0-alpha.3
  google_maps_flutter: ^2.2.2
  geocoding: ^2.0.0
  geolocator: ^8.2.0
  syncfusion_flutter_datepicker: ^24.2.9
  textfield_tags: ^3.0.1
  http: ^1.2.1
  path: ^1.8.2
  typed_data: ^1.3.1
  http_parser: ^4.0.2
  animated_floating_buttons: ^0.0.2
  flutter_native_splash:
  emoji_picker_flutter: ^1.6.2

dev_dependencies:
  icons_launcher:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: 'assets/image/ic_launcher.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true

flutter_icons:
  ios: true
  android: true
  image_path: 'assets/image/ic_launcher.png'

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/font/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/font/ubuntu/Ubuntu-Bold.ttf
          weight: 600
